projects:
  app:
    schemaPath: src/schema/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
  prisma:
    schemaPath: src/schema/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
